# DataPath — Week 3: Data Cleaning — SOLUTIONS
**Art.Ificial · Spring 2026**

Today we're doing two things:
1. Learning the basic pandas commands you'll use all project
2. Cleaning our dataset so it's ready for analysis

Work through each cell top to bottom. Press **Shift + Enter** to run a cell.

---
## Part 1 — Pandas Basics
Pandas is the main Python library for working with data. Think of it as Excel inside Python.

A **DataFrame** is just a table — rows and columns, like a spreadsheet.

In [1]:
# First, import the libraries we need
# pandas = working with data tables
# numpy = math operations

import pandas as pd
import numpy as np

print("Libraries loaded successfully!")

Libraries loaded successfully!

In [2]:
# Load the dataset
# Make sure the CSV file is in the same folder as this notebook
# or provide the full path

df = pd.read_csv("../data/raw/YouTube-TikTok Trends Dataset/youtube_shorts_tiktok_trends_2025.csv")

print(f"Dataset loaded! Shape: {df.shape}")
print(f"That means {df.shape[0]} rows and {df.shape[1]} columns")

Dataset loaded! Shape: (48079, 58)
That means 48079 rows and 58 columns

In [3]:
# .head() shows the first 5 rows
# This is always the first thing you run on a new dataset
# Just to see what you're working with

df.head()

,platform,country,region,language,category,hashtag,title_keywords,author_handle,sound_type,music_track,...,traffic_source,is_weekend,row_id,engagement_total,like_rate,dislike_rate,engagement_per_1k,engagement_like_rate,engagement_comment_rate,engagement_share_rate
0,TikTok,Jp,Asia,ja,Gaming,#Lifestyle,Night Routine — College,NextVision,trending,8bit loop,...,External,1,2e681528d17a1fe1986857942536ec27,30317,0.086159,0.004004,120.069,0.086159,0.012555,0.007830
1,TikTok,Se,Europe,sv,Food,#Sports,Morning Routine — College,DailyVlogsDiego,trending,Street vibe,...,Search,0,2e35fa0b2978b9cae635839c1d4e9e74,30577,0.085298,0.002421,113.005,0.085298,0.007850,0.007791
2,TikTok,Za,Africa,en,Art,#Workout,Night Routine — College,BeyondHub,licensed,Gallery pad,...,External,1,0d88a011235a82244995ef52961f9502,503,0.049154,0.001625,68.111,0.049154,0.004469,0.005146
3,TikTok,Kr,Asia,ko,News,#Esports,Best Settings for Fortnite,NextHub,original,Neutral piano,...,Search,1,e15cff7621ed3f9eb9d2c97c841be0f3,7828,0.086257,0.003164,108.156,0.086257,0.011205,0.005292
4,TikTok,Au,Oceania,en,Beauty,#Comedy,When your friend is Beginners,LucasOfficial,licensed,Soft glam loop,...,ForYou,1,d696b4f0a50ea70e7cb5021be7e198ec,1171,0.051441,0.001175,72.400,0.051441,0.004204,0.004142

In [4]:
# .info() shows every column, its data type, and how many non-null values it has
# 'non-null' means the cell actually has a value (not empty)
# If a column has fewer non-null values than total rows, it has missing data

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48079 entries, 0 to 48078
Data columns (total 58 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   platform                 48079 non-null  object
 1   country                  48079 non-null  object
 2   region                   48079 non-null  object
 3   language                 48079 non-null  object
 4   category                 48079 non-null  object
 5   hashtag                  48079 non-null  object
 6   title_keywords           48079 non-null  object
 7   author_handle            48079 non-null  object
 8   sound_type               48079 non-null  object
 9   music_track              48079 non-null  object
 10  week_of_year             48079 non-null  int64
 11  duration_sec             48079 non-null  int64
 12  views                    48079 non-null  int64
 13  likes                    48079 non-null  int64
 14  comments                 48079 non-null  int64
 15  shares                   48079 non-null  int64
 16  saves                    48079 non-null  int64
 17  engagement_rate          48079 non-null  float64
 18  trend_label              48079 non-null  object
 19  source_hint              48079 non-null  object
 20  notes                    48079 non-null  object
 21  device_type              48079 non-null  object
 22  upload_hour              48079 non-null  int64
 23  genre                    48079 non-null  object
 24  trend_duration_days      48079 non-null  int64
 25  trend_type               48079 non-null  object
 26  engagement_velocity      48079 non-null  float64
 27  dislikes                 48079 non-null  int64
 28  comment_ratio            48079 non-null  float64
 29  share_rate               48079 non-null  float64
 30  save_rate                48079 non-null  float64
 31  like_dislike_ratio       48079 non-null  float64
 32  publish_dayofweek        48079 non-null  object
 33  publish_period           48079 non-null  object
 34  event_season             48079 non-null  object
 35  tags                     48079 non-null  object
 36  sample_comments          48079 non-null  object
 37  creator_avg_views        48079 non-null  float64
 38  creator_tier             48079 non-null  object
 39  season                   48079 non-null  object
 40  publish_date_approx      48079 non-null  object
 41  year_month               48079 non-null  object
 42  title                    48079 non-null  object
 43  title_length             48079 non-null  int64
 44  has_emoji                48079 non-null  int64
 45  avg_watch_time_sec       48079 non-null  float64
 46  completion_rate          48079 non-null  float64
 47  device_brand             48079 non-null  object
 48  traffic_source           48079 non-null  object
 49  is_weekend               48079 non-null  int64
 50  row_id                   48079 non-null  object
 51  engagement_total         48079 non-null  int64
 52  like_rate                48079 non-null  float64
 53  dislike_rate             48079 non-null  float64
 54  engagement_per_1k        48079 non-null  float64
 55  engagement_like_rate     48079 non-null  float64
 56  engagement_comment_rate  48079 non-null  float64
 57  engagement_share_rate    48079 non-null  float64
dtypes: float64(15), int64(14), object(29)
memory usage: 21.3+ MB

In [5]:
# .isnull().sum() counts how many missing values are in each column
# Any column with a number > 0 has gaps we need to deal with

print("Missing values per column:")
print(df.isnull().sum())

Missing values per column:
platform                   0
country                    0
region                     0
language                   0
category                   0
hashtag                    0
title_keywords             0
author_handle              0
sound_type                 0
music_track                0
week_of_year               0
duration_sec               0
views                      0
likes                      0
comments                   0
shares                     0
saves                      0
engagement_rate            0
trend_label                0
source_hint                0
notes                      0
device_type                0
upload_hour                0
genre                      0
trend_duration_days        0
trend_type                 0
engagement_velocity        0
dislikes                   0
comment_ratio              0
share_rate                 0
save_rate                  0
like_dislike_ratio         0
publish_dayofweek          0
publish_period             0
event_season               0
tags                       0
sample_comments            0
creator_avg_views          0
creator_tier               0
season                     0
publish_date_approx        0
year_month                 0
title                      0
title_length               0
has_emoji                  0
avg_watch_time_sec         0
completion_rate            0
device_brand               0
traffic_source             0
is_weekend                 0
row_id                     0
engagement_total           0
like_rate                  0
dislike_rate               0
engagement_per_1k          0
engagement_like_rate       0
engagement_comment_rate    0
engagement_share_rate      0
dtype: int64

In [6]:
# .describe() gives you basic statistics for every numeric column
# min, max, mean, median (50%) — useful for spotting weird values

df.describe()

,week_of_year,duration_sec,views,likes,comments,shares,saves,engagement_rate,upload_hour,trend_duration_days,...,avg_watch_time_sec,completion_rate,is_weekend,engagement_total,like_rate,dislike_rate,engagement_per_1k,engagement_like_rate,engagement_comment_rate,engagement_share_rate
count,48079.000000,48079.000000,4.807900e+04,48079.000000,48079.000000,48079.000000,48079.000000,48079.000000,48079.000000,48079.000000,...,48079.000000,48079.000000,48079.000000,48079.000000,48079.000000,48079.000000,48079.000000,48079.000000,48079.000000,48079.000000
mean,18.234260,34.489320,9.929276e+04,5737.732108,628.657314,553.484494,591.071487,0.075415,15.986751,13.742923,...,21.662460,0.635308,0.622995,7510.945402,0.057607,0.002462,75.415322,0.057607,0.006310,0.005556
std,9.996924,16.401608,1.318522e+05,8639.923653,967.782704,849.436172,978.280616,0.030091,5.489399,13.343582,...,10.583019,0.112604,0.484641,11262.284575,0.023123,0.001586,30.090519,0.023123,0.002969,0.002496
min,1.000000,5.000000,7.940000e+02,33.000000,3.000000,3.000000,2.000000,0.014720,0.000000,3.000000,...,2.800000,0.400000,0.000000,43.000000,0.011792,0.000000,14.720000,0.011792,0.000975,0.000735
25%,10.000000,22.000000,3.032250e+04,1526.000000,160.000000,143.000000,138.000000,0.052326,13.000000,5.000000,...,14.000000,0.548000,0.000000,1998.000000,0.039941,0.001273,52.326000,0.039941,0.004058,0.003670
50%,18.000000,31.000000,5.962000e+04,3167.000000,339.000000,301.000000,301.000000,0.071575,17.000000,7.000000,...,19.400000,0.635000,1.000000,4159.000000,0.054654,0.002138,71.575000,0.054654,0.005809,0.005163
75%,27.000000,43.000000,1.180945e+05,6618.000000,720.000000,635.000000,659.500000,0.094794,20.000000,17.000000,...,27.000000,0.724000,1.000000,8675.000000,0.072280,0.003276,94.793500,0.072281,0.008016,0.007000
max,35.000000,90.000000,3.080686e+06,310916.000000,31776.000000,29004.000000,29679.000000,0.235819,23.000000,60.000000,...,67.300000,0.850000,1.000000,390142.000000,0.185300,0.012718,235.819000,0.185300,0.023668,0.020328

In [7]:
# Let's see what platforms are in the dataset
# .value_counts() counts how many times each unique value appears

print("Platform breakdown:")
print(df["platform"].value_counts())

print("\nTrend labels:")
print(df["trend_label"].value_counts())

Platform breakdown:
platform
TikTok     28844
YouTube    19235
Name: count, dtype: int64

Trend labels:
trend_label
seasonal     12146
rising       12102
declining    12003
stable       11828
Name: count, dtype: int64

In [8]:
# Let's look at the columns we actually care about for this project
# You can select specific columns like this:

df[["platform", "views", "likes", "duration_sec", "engagement_rate"]].head(10)

  platform   views  likes  duration_sec  engagement_rate
0   TikTok  252497  21755            40         0.120069
1   TikTok  270580  23080            18         0.113005
2   TikTok    7385    363            22         0.068111
3   TikTok   72377   6243            36         0.108156
4   TikTok   16174    832            35         0.072400
5   TikTok   47449   2462            33         0.065671
6   TikTok   27099   1868            26         0.097753
7   TikTok  172755   8917            18         0.064363
8   TikTok  166299   7577            31         0.055779
9   TikTok  136110   7911            34         0.071494

---
## Part 2 — Data Cleaning

Cleaning means:
- Removing duplicate rows
- Dropping rows with missing values in columns we need
- Removing rows with nonsense values (e.g. 0 views)
- Adding useful derived columns
- Keeping only the columns we actually need

We always work on a **copy** of the original data so we never lose anything.

In [9]:
# Step 0 — make a copy so we never touch the original
# Think of df as the locked original, clean as our working copy

clean = df.copy()
print(f"Starting rows: {len(clean)}")

Starting rows: 48079

In [10]:
# Step 1 — remove duplicate rows
# A duplicate is a row that is identical to another row in every column
# These can sneak in when datasets are merged or scraped multiple times

before = len(clean)
clean = clean.drop_duplicates()
after = len(clean)

print(f"Removed {before - after} duplicate rows")
print(f"Rows remaining: {after}")

Removed 0 duplicate rows
Rows remaining: 48079

In [11]:
# Step 2 — drop rows with missing values in critical columns
# We can't analyze a video if we don't know its views, duration, or platform
# .dropna(subset=[...]) removes any row where ANY of those columns is empty

critical_columns = ["views", "likes", "duration_sec", "platform", "engagement_rate"]

before = len(clean)
clean = clean.dropna(subset=critical_columns)
after = len(clean)

print(f"Removed {before - after} rows with missing critical values")
print(f"Rows remaining: {after}")

Removed 0 rows with missing critical values
Rows remaining: 48079

In [12]:
# Step 3 — remove nonsense values
# A video with 0 views or 0 duration shouldn't exist
# Shorts are max 3 minutes (180 seconds) — anything longer isn't a Short

# In Part 1 you saw how boolean filtering works: df[df["column"] > value]
# Now you write them. The first one is done as an example.

before = len(clean)

clean = clean[clean["views"] > 0]           # keep rows where views > 0
clean = clean[clean["likes"] >= 0]          # SOLUTION: likes can be 0, not negative
clean = clean[clean["duration_sec"] > 0]    # SOLUTION: duration must be positive
clean = clean[clean["duration_sec"] <= 180] # SOLUTION: max short length is 180s

after = len(clean)
print(f"Removed {before - after} rows with nonsense values")
print(f"Rows remaining: {after}")

Removed 0 rows with nonsense values
Rows remaining: 48079

In [13]:
# Step 4 — handle outliers
# Outliers are extreme values that can skew your analysis
# We'll cap views at the 99th percentile
# This means: find the value that 99% of videos are below, remove anything above it

p99 = clean["views"].quantile(0.99)
print(f"99th percentile of views: {p99:,.0f}")
print(f"Max views before: {clean['views'].max():,.0f}")

before = len(clean)
clean = clean[clean["views"] <= p99]
after = len(clean)

print(f"\nRemoved {before - after} extreme outlier rows")
print(f"Max views after: {clean['views'].max():,.0f}")
print(f"Rows remaining: {after}")

99th percentile of views: 628,991
Max views before: 3,080,686

Removed 481 extreme outlier rows
Max views after: 628,903
Rows remaining: 47598

In [14]:
# Step 5 — add derived columns
# These are new columns we calculate from existing ones
# They will be useful features for our model later

# title_length: how many characters is the title?
clean["title_length"] = clean["title"].str.len()

# duration bucket: group videos into length categories
# This helps us answer: do shorter videos perform better?
def duration_bucket(seconds):
    if seconds <= 15:
        return "0-15s"
    elif seconds <= 30:
        return "15-30s"
    elif seconds <= 60:
        return "30-60s"
    else:
        return "60-180s"

clean["duration_bucket"] = clean["duration_sec"].apply(duration_bucket)

# is_viral: binary column based on our agreed definition
# Top 10% of views = viral
viral_threshold = clean["views"].quantile(0.90)
clean["is_viral"] = (clean["views"] >= viral_threshold).astype(int)

print(f"Viral threshold (top 10%): {viral_threshold:,.0f} views")
print(f"Viral videos: {clean['is_viral'].sum():,}")
print(f"Non-viral videos: {(clean['is_viral'] == 0).sum():,}")
print(f"\nDuration bucket breakdown:")
print(clean["duration_bucket"].value_counts())

Viral threshold (top 10%): 206,748 views
Viral videos: 4,760
Non-viral videos: 42,838

Duration bucket breakdown:
duration_bucket
30-60s     20727
15-30s     19462
60-180s     3902
0-15s       3507
Name: count, dtype: int64

In [15]:
# Step 6 — keep only the columns we need
# Our dataset has 57 columns — we only need about 20
# Keeping only what we need makes everything faster and easier to read

# YOUR TURN: select only the columns below from clean
# Hint: in Part 1 you did df[["col1", "col2"]] to pick specific columns — same idea here

keep_columns = [
    # identity
    "platform", "category", "country",
    # performance metrics
    "views", "likes", "comments", "shares", "saves", "engagement_rate", "completion_rate",
    # video features
    "duration_sec", "duration_bucket", "upload_hour", "publish_dayofweek",
    "is_weekend", "music_track", "sound_type", "has_emoji",
    # derived
    "title_length", "is_viral", "trend_label", "creator_tier",
]

clean = clean[keep_columns]  # SOLUTION: pass the list inside df[[...]] to select columns

print(f"Columns reduced from {len(df.columns)} to {len(clean.columns)}")
print(f"Final shape: {clean.shape}")
clean.head()

Columns reduced from 58 to 22
Final shape: (47598, 22)

,platform,category,country,views,likes,comments,shares,saves,engagement_rate,completion_rate,...,upload_hour,publish_dayofweek,is_weekend,music_track,sound_type,has_emoji,title_length,is_viral,trend_label,creator_tier
0,TikTok,Gaming,Jp,252497,21755,3170,1977,3415,0.120069,0.645,...,15,Saturday,1,8bit loop,trending,1,31,1,rising,Mid
1,TikTok,Food,Se,270580,23080,2124,2108,3265,0.113005,0.578,...,3,Wednesday,0,Street vibe,trending,1,24,1,declining,Mid
2,TikTok,Art,Za,7385,363,33,38,69,0.068111,0.532,...,15,Sunday,1,Gallery pad,licensed,0,22,0,seasonal,Mid
3,TikTok,News,Kr,72377,6243,811,383,391,0.108156,0.658,...,15,Friday,1,Neutral piano,original,1,30,0,declining,Mid
4,TikTok,Beauty,Au,16174,832,68,67,204,0.072400,0.703,...,18,Saturday,1,Soft glam loop,licensed,1,13,0,seasonal,Mid

In [16]:
# Step 7 — final check before saving
# YOUR TURN: use what you learned in Part 1 to answer these three questions.
# Each one has a hint pointing back to the Part 1 cell where you saw it.

print("=== FINAL DATASET SUMMARY ===")
print(f"Total rows: {len(clean):,}")
print(f"Total columns: {len(clean.columns)}")

# Q1: How many missing values are in each column?
print(f"\nMissing values:")
print(clean.isnull().sum())  # SOLUTION

# Q2: What's the platform breakdown (how many videos per platform)?
print(f"\nPlatform split:")
print(clean["platform"].value_counts())  # SOLUTION

# Q3: How many viral vs non-viral videos are there?
print(f"\nViral vs non-viral:")
print(clean["is_viral"].value_counts())  # SOLUTION

# This one is filled in for you — just run it
print(f"\nViews stats:")
print(clean["views"].describe().apply(lambda x: f"{x:,.0f}"))

=== FINAL DATASET SUMMARY ===
Total rows: 47,598
Total columns: 22

Missing values:
platform             0
category             0
country              0
views                0
likes                0
comments             0
shares               0
saves                0
engagement_rate      0
completion_rate      0
duration_sec         0
duration_bucket      0
upload_hour          0
publish_dayofweek    0
is_weekend           0
music_track          0
sound_type           0
has_emoji            0
title_length         0
is_viral             0
trend_label          0
creator_tier         0
dtype: int64

Platform split:
platform
TikTok     28543
YouTube    19055
Name: count, dtype: int64

Viral vs non-viral:
is_viral
0    42838
1     4760
Name: count, dtype: int64

Views stats:
count     47,598
mean      90,737
std       93,590
min          794
25%       30,085
50%       58,905
75%      115,192
max      628,903
Name: views, dtype: object

In [17]:
# Step 8 — save the clean dataset
# index=False means don't write the row numbers as a column

clean.to_csv("clean_dataset.csv", index=False)

print("Saved to clean_dataset.csv")
print("Upload this file to Google Drive in the /data/clean folder")
print("Push this notebook to GitHub in the /notebooks folder")

Saved to clean_dataset.csv
Upload this file to Google Drive in the /data/clean folder
Push this notebook to GitHub in the /notebooks folder

---
## Part 3 — Quick Sanity Check
Load the saved CSV back and confirm it looks exactly right.
This is good practice — always verify your saved file loads correctly.

In [18]:
# Load the clean file back to confirm it saved correctly
verify = pd.read_csv("clean_dataset.csv")

print(f"Rows: {len(verify):,}")
print(f"Columns: {list(verify.columns)}")
verify.head()

Rows: 47,598
Columns: ['platform', 'category', 'country', 'views', 'likes', 'comments', 'shares', 'saves', 'engagement_rate', 'completion_rate', 'duration_sec', 'duration_bucket', 'upload_hour', 'publish_dayofweek', 'is_weekend', 'music_track', 'sound_type', 'has_emoji', 'title_length', 'is_viral', 'trend_label', 'creator_tier']

,platform,category,country,views,likes,comments,shares,saves,engagement_rate,completion_rate,...,upload_hour,publish_dayofweek,is_weekend,music_track,sound_type,has_emoji,title_length,is_viral,trend_label,creator_tier
0,TikTok,Gaming,Jp,252497,21755,3170,1977,3415,0.120069,0.645,...,15,Saturday,1,8bit loop,trending,1,31,1,rising,Mid
1,TikTok,Food,Se,270580,23080,2124,2108,3265,0.113005,0.578,...,3,Wednesday,0,Street vibe,trending,1,24,1,declining,Mid
2,TikTok,Art,Za,7385,363,33,38,69,0.068111,0.532,...,15,Sunday,1,Gallery pad,licensed,0,22,0,seasonal,Mid
3,TikTok,News,Kr,72377,6243,811,383,391,0.108156,0.658,...,15,Friday,1,Neutral piano,original,1,30,0,declining,Mid
4,TikTok,Beauty,Au,16174,832,68,67,204,0.072400,0.703,...,18,Saturday,1,Soft glam loop,licensed,1,13,0,seasonal,Mid

---
## Done!

**What we built today:**
- A clean dataset with ~48,000 videos from TikTok and YouTube
- Removed duplicates, nulls, and nonsense values
- Added `is_viral`, `duration_bucket`, and `title_length` columns
- Reduced from 57 columns to 22 focused columns

**Before you leave:**
1. Upload `clean_dataset.csv` to Google Drive `/data/clean`
2. Push this notebook to GitHub `/notebooks`

**Next week (Week 4):** We use this clean data to start finding patterns — do shorter videos go more viral? Does upload time matter? Does platform matter?